package com.example.mob_final_app.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.mob_final_app.data.model.Car
import com.example.mob_final_app.data.repository.CarRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

class CarViewModel(private val repository: CarRepository) : ViewModel() {

    private val _minHorsepower = MutableStateFlow(0)
    val minHorsepower: StateFlow<Int> = _minHorsepower.asStateFlow()

    fun setMinHorsepower(hp: Int) {
        _minHorsepower.value = hp
    }

    val allCars: StateFlow<List<Car>> = repository.allCars.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = emptyList()
    )

    fun insert(car: Car) = viewModelScope.launch {
        repository.insert(car)
    }

    fun insertAll(cars: List<Car>) = viewModelScope.launch {
        repository.insertAll(cars)
    }

    suspend fun getCarById(id: Int): Car? {
        return repository.getCarById(id)
    }
    
    // Initial data setup
    fun prepopulateData() {
        viewModelScope.launch {
            val sampleCars = listOf(
                // Gas Cars (40)
                Car(brand = "Toyota", model = "Supra", year = 2024, engine = "3.0L Turbo I6", horsepower = 382, transmission = "8-speed Automatic", description = "The legend returns with even more power and precision.", category = "Gas", fuelEfficiency = "23/31 MPG", imageUrl = "supra"),
                Car(brand = "BMW", model = "M4", year = 2024, engine = "3.0L Twin-Turbo I6", horsepower = 503, transmission = "8-speed Automatic", description = "Performance and luxury combined in a sleek coupe.", category = "Gas", fuelEfficiency = "16/23 MPG", imageUrl = "bmwm4"),
                Car(brand = "Porsche", model = "911 GT3", year = 2024, engine = "4.0L Flat-6", horsepower = 502, transmission = "7-speed PDK", description = "A race car for the road, offering an unmatched driving experience.", category = "Gas", fuelEfficiency = "15/18 MPG", imageUrl = "porsche911gt3"),
                Car(brand = "Nissan", model = "GT-R", year = 2024, engine = "3.8L Twin-Turbo V6", horsepower = 565, transmission = "6-speed Dual-Clutch", description = "Godzilla remains a formidable force on the track.", category = "Gas", fuelEfficiency = "16/22 MPG", imageUrl = "nissangtr"),
                Car(brand = "Ford", model = "Mustang GT", year = 2024, engine = "5.0L V8", horsepower = 480, transmission = "6-speed Manual", description = "The classic American pony car with a roaring V8.", category = "Gas", fuelEfficiency = "15/24 MPG", imageUrl = "mustanggt"),
                Car(brand = "Chevrolet", model = "Corvette Z06", year = 2024, engine = "5.5L V8", horsepower = 670, transmission = "8-speed Dual-Clutch", description = "A mid-engine masterpiece with a flat-plane crank V8.", category = "Gas", fuelEfficiency = "12/19 MPG", imageUrl = "corvettez06"),
                Car(brand = "Lamborghini", model = "Huracán Sterrato", year = 2024, engine = "5.2L V10", horsepower = 602, transmission = "7-speed Dual-Clutch", description = "An all-terrain supercar designed for maximum driving fun.", category = "Gas", fuelEfficiency = "13/18 MPG", imageUrl = "huracansterrato"),
                Car(brand = "Dodge", model = "Challenger SRT Hellcat", year = 2023, engine = "6.2L Supercharged V8", horsepower = 717, transmission = "8-speed Automatic", description = "Pure American muscle with overwhelming power.", category = "Gas", fuelEfficiency = "13/22 MPG", imageUrl = "challengersrt"),
                Car(brand = "Ferrari", model = "812 Superfast", year = 2023, engine = "6.5L V12", horsepower = 789, transmission = "7-speed Dual-Clutch", description = "A front-engine V12 masterpiece of speed and sound.", category = "Gas", fuelEfficiency = "12/16 MPG", imageUrl = "ferrari812superfast"),
                Car(brand = "Aston Martin", model = "DBS", year = 2024, engine = "5.2L Twin-Turbo V12", horsepower = 715, transmission = "8-speed Automatic", description = "The ultimate GT car with effortless performance.", category = "Gas", fuelEfficiency = "14/22 MPG", imageUrl = "dbs"),
                Car(brand = "Mercedes-AMG", model = "GT Black Series", year = 2021, engine = "4.0L Twin-Turbo V8", horsepower = 720, transmission = "7-speed Dual-Clutch", description = "A track-focused beast with advanced aerodynamics.", category = "Gas", fuelEfficiency = "13/18 MPG", imageUrl = "gtblackseries"),
                Car(brand = "Pagani", model = "Huayra", year = 2023, engine = "6.0L Twin-Turbo V12", horsepower = 730, transmission = "7-speed Sequential", description = "Art on wheels with extreme performance and craftsmanship.", category = "Gas", fuelEfficiency = "10/14 MPG", imageUrl = "huayra"),
                Car(brand = "McLaren", model = "720S", year = 2023, engine = "4.0L Twin-Turbo V8", horsepower = 710, transmission = "7-speed Dual-Clutch", description = "Lightweight and incredibly fast supercar.", category = "Gas", fuelEfficiency = "15/22 MPG", imageUrl = "mclaren720s"),
                Car(brand = "Lamborghini", model = "Aventador SVJ", year = 2022, engine = "6.5L V12", horsepower = 759, transmission = "7-speed ISR", description = "Pure V12 performance with aggressive aero.", category = "Gas", fuelEfficiency = "9/15 MPG", imageUrl = "avendatorsvj"),
                Car(brand = "Porsche", model = "911 Turbo S", year = 2024, engine = "3.7L Twin-Turbo Flat-6", horsepower = 640, transmission = "8-speed PDK", description = "The benchmark for everyday usable supercars.", category = "Gas", fuelEfficiency = "15/20 MPG", imageUrl = "turbos"),
                Car(brand = "Bugatti", model = "Chiron", year = 2022, engine = "8.0L Quad-Turbo W16", horsepower = 1500, transmission = "7-speed Dual-Clutch", description = "Engineering at its absolute peak, redefined performance.", category = "Gas", fuelEfficiency = "9/14 MPG", imageUrl = "chiron"),
                Car(brand = "Koenigsegg", model = "Jesko", year = 2024, engine = "5.0L Twin-Turbo V8", horsepower = 1600, transmission = "9-speed LST", description = "A track weapon with revolutionary transmission tech.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "jesko"),
                Car(brand = "McLaren", model = "Senna", year = 2023, engine = "4.0L Twin-Turbo V8", horsepower = 789, transmission = "7-speed Dual-Clutch", description = "Uncompromising performance for the track.", category = "Gas", fuelEfficiency = "14/18 MPG", imageUrl = "senna"),
                Car(brand = "Ford", model = "GT", year = 2022, engine = "3.5L Twin-Turbo V6", horsepower = 660, transmission = "7-speed Dual-Clutch", description = "American heritage meets cutting-edge aero.", category = "Gas", fuelEfficiency = "12/18 MPG", imageUrl = "fordgt"),
                Car(brand = "Nissan", model = "Z", year = 2024, engine = "3.0L Twin-Turbo V6", horsepower = 400, transmission = "6-speed Manual", description = "A modern take on the legendary Z heritage.", category = "Gas", fuelEfficiency = "18/24 MPG", imageUrl = "nissanz"),
                Car(brand = "Aston Martin", model = "Vantage", year = 2024, engine = "4.0L Twin-Turbo V8", horsepower = 656, transmission = "8-speed Automatic", description = "A born predator, with a redesigned interior and massive power jump.", category = "Gas", fuelEfficiency = "18/24 MPG", imageUrl = "vantage"),
                Car(brand = "Lotus", model = "Emira", year = 2024, engine = "3.5L Supercharged V6", horsepower = 400, transmission = "6-speed Manual", description = "The last internal combustion car from Lotus, pure driver focus.", category = "Gas", fuelEfficiency = "16/24 MPG", imageUrl = "emira"),
                Car(brand = "Jaguar", model = "F-Type R", year = 2024, engine = "5.0L Supercharged V8", horsepower = 575, transmission = "8-speed Automatic", description = "The final celebration of Jaguar's internal combustion sports cars.", category = "Gas", fuelEfficiency = "16/24 MPG", imageUrl = "ftyper"),
                Car(brand = "Bentley", model = "Continental GT Speed", year = 2024, engine = "6.0L Twin-Turbo W12", horsepower = 650, transmission = "8-speed Dual-Clutch", description = "The pinnacle of luxury grand touring performance.", category = "Gas", fuelEfficiency = "12/20 MPG", imageUrl = "continentalgtspeed"),
                Car(brand = "Cadillac", model = "CT5-V Blackwing", year = 2024, engine = "6.2L Supercharged V8", horsepower = 668, transmission = "6-speed Manual", description = "A track-capable luxury sedan with an available manual transmission.", category = "Gas", fuelEfficiency = "13/21 MPG", imageUrl = "ct5vblackwing"),
                Car(brand = "Audi", model = "RS 6 Avant", year = 2024, engine = "4.0L Twin-Turbo V8", horsepower = 621, transmission = "8-speed Automatic", description = "The ultimate performance wagon for the family.", category = "Gas", fuelEfficiency = "14/22 MPG", imageUrl = "rs6avant"),
                Car(brand = "Lamborghini", model = "Urus Performante", year = 2024, engine = "4.0L Twin-Turbo V8", horsepower = 657, transmission = "8-speed Automatic", description = "The super SUV that behaves like a supercar.", category = "Gas", fuelEfficiency = "12/17 MPG", imageUrl = "urusperformante"),
                Car(brand = "Ferrari", model = "Purosangue", year = 2024, engine = "6.5L V12", horsepower = 715, transmission = "8-speed Dual-Clutch", description = "Ferrari's first four-door, four-seater with a naturally aspirated V12.", category = "Gas", fuelEfficiency = "12/15 MPG", imageUrl = "purosangue"),
                Car(brand = "Maserati", model = "MC20", year = 2024, engine = "3.0L Twin-Turbo V6", horsepower = 621, transmission = "8-speed Dual-Clutch", description = "Italian style meets the innovative Nettuno engine.", category = "Gas", fuelEfficiency = "15/25 MPG", imageUrl = "mc20"),
                Car(brand = "Alfa Romeo", model = "Giulia Quadrifoglio", year = 2024, engine = "2.9L Twin-Turbo V6", horsepower = 505, transmission = "8-speed Automatic", description = "Pure Italian passion and precision in a sports sedan.", category = "Gas", fuelEfficiency = "17/25 MPG", imageUrl = "giuliaquadrifoglio"),
                Car(brand = "Bugatti", model = "Mistral", year = 2024, engine = "8.0L Quad-Turbo W16", horsepower = 1578, transmission = "7-speed Dual-Clutch", description = "The ultimate roadster, a final masterpiece for the W16 engine.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "mistral"),
                Car(brand = "Hennessey", model = "Venom F5", year = 2023, engine = "6.6L Twin-Turbo V8", horsepower = 1817, transmission = "7-speed Single-Clutch", description = "Built to be the fastest road car on Earth.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "venom_f5"),
                Car(brand = "SSC", model = "Tuatara", year = 2023, engine = "5.9L Twin-Turbo V8", horsepower = 1750, transmission = "7-speed AMT", description = "A high-speed marvel designed for world records.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "tuatara"),
                Car(brand = "Gordon Murray", model = "T.50", year = 2024, engine = "3.9L V12", horsepower = 654, transmission = "6-speed Manual", description = "The purest, lightest, most driver-centric supercar ever.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "t_50"),
                Car(brand = "Zenvo", model = "TSR-S", year = 2023, engine = "5.8L Twin-Supercharged V8", horsepower = 1177, transmission = "7-speed Sequential", description = "Features a unique tilting Centripetal Wing.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "tsr_s"),
                Car(brand = "Apollo", model = "Intensa Emozione", year = 2022, engine = "6.3L V12", horsepower = 780, transmission = "6-speed Sequential", description = "A modern tribute to the GT1 era of racing.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "intensa_emozione"),
                Car(brand = "Koenigsegg", model = "Agera RS", year = 2018, engine = "5.0L Twin-Turbo V8", horsepower = 1160, transmission = "7-speed Dual-Clutch", description = "The record-shattering hypercar that redefined physics.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "agera_rs"),
                Car(brand = "Saleen", model = "S7 LM", year = 2019, engine = "7.0L Twin-Turbo V8", horsepower = 1300, transmission = "6-speed Manual", description = "An American supercar legend with extreme aero.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "s7_lm"),
                Car(brand = "Gumpert", model = "Apollo", year = 2010, engine = "4.2L Twin-Turbo V8", horsepower = 641, transmission = "6-speed Sequential", description = "A track beast that prioritizes function over form.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "apollo"),
                Car(brand = "Noble", model = "M600", year = 2023, engine = "4.4L Twin-Turbo V8", horsepower = 650, transmission = "6-speed Manual", description = "Analog driving at its finest, no electronic aids.", category = "Gas", fuelEfficiency = "N/A", imageUrl = "m600"),

                // Hybrid Cars (40)
                Car(brand = "Toyota", model = "Prius", year = 2024, engine = "2.0L Hybrid", horsepower = 194, transmission = "eCVT", description = "The efficiency king gets a stylish new look.", category = "Hybrid", fuelEfficiency = "57/56 MPG", imageUrl = "prius"),
                Car(brand = "Honda", model = "Accord Hybrid", year = 2024, engine = "2.0L Hybrid", horsepower = 204, transmission = "eCVT", description = "A sophisticated sedan with impressive fuel economy.", category = "Hybrid", fuelEfficiency = "51/44 MPG", imageUrl = "accord"),
                Car(brand = "BMW", model = "XM", year = 2024, engine = "4.4L V8 Plug-in Hybrid", horsepower = 644, transmission = "8-speed Automatic", description = "A high-performance luxury SUV with hybrid power.", category = "Hybrid", fuelEfficiency = "46 MPGe", imageUrl = "xm"),
                Car(brand = "McLaren", model = "Artura", year = 2024, engine = "3.0L V6 Hybrid", horsepower = 671, transmission = "8-speed Dual-Clutch", description = "The next generation of supercar performance.", category = "Hybrid", fuelEfficiency = "39 MPGe", imageUrl = "artura"),
                Car(brand = "Ferrari", model = "296 GTB", year = 2024, engine = "2.9L V6 Hybrid", horsepower = 818, transmission = "8-speed Dual-Clutch", description = "Defining the concept of fun to drive with hybrid technology.", category = "Hybrid", fuelEfficiency = "47 MPGe", imageUrl = "ferrari296gtb"),
                Car(brand = "Lexus", model = "LC 500h", year = 2024, engine = "3.5L V6 Hybrid", horsepower = 354, transmission = "Multi-stage Hybrid", description = "Exquisite design meets advanced hybrid efficiency.", category = "Hybrid", fuelEfficiency = "26/33 MPG", imageUrl = "lc500h"),
                Car(brand = "Porsche", model = "Cayenne E-Hybrid", year = 2024, engine = "3.0L V6 Hybrid", horsepower = 463, transmission = "8-speed Automatic", description = "Versatile luxury SUV with plug-in hybrid performance.", category = "Hybrid", fuelEfficiency = "47 MPGe", imageUrl = "cayenne"),
                Car(brand = "Lamborghini", model = "Revuelto", year = 2024, engine = "6.5L V12 Hybrid", horsepower = 1001, transmission = "8-speed Dual-Clutch", description = "The first HPEV V12 hybrid supercar.", category = "Hybrid", fuelEfficiency = "23 MPGe", imageUrl = "revuelto"),
                Car(brand = "Chevrolet", model = "Corvette E-Ray", year = 2024, engine = "6.2L V8 Hybrid", horsepower = 655, transmission = "8-speed Dual-Clutch", description = "All-wheel drive hybrid performance in a Corvette.", category = "Hybrid", fuelEfficiency = "19 MPG", imageUrl = "corvette_e_ray"),
                Car(brand = "Mercedes-AMG", model = "S 63 E Performance", year = 2024, engine = "4.0L V8 Hybrid", horsepower = 791, transmission = "9-speed Automatic", description = "The most powerful S-Class ever with hybrid tech.", category = "Hybrid", fuelEfficiency = "33 MPGe", imageUrl = "s_63_e_performance"),
                Car(brand = "Porsche", model = "Panamera Turbo E-Hybrid", year = 2024, engine = "4.0L V8 Hybrid", horsepower = 670, transmission = "8-speed PDK", description = "Luxury sedan with sports car performance and hybrid efficiency.", category = "Hybrid", fuelEfficiency = "50 MPGe", imageUrl = "panamera_turbo_e_hybrid"),
                Car(brand = "BMW", model = "330e", year = 2024, engine = "2.0L I4 Hybrid", horsepower = 288, transmission = "8-speed Automatic", description = "The ultimate driving machine with plug-in hybrid versatility.", category = "Hybrid", fuelEfficiency = "73 MPGe", imageUrl = "bwm330e"),
                Car(brand = "Honda", model = "NSX Type S", year = 2022, engine = "3.5L V6 Hybrid", horsepower = 600, transmission = "9-speed Dual-Clutch", description = "The final and most powerful version of the hybrid NSX.", category = "Hybrid", fuelEfficiency = "21 MPG", imageUrl = "nsx_type_s"),
                Car(brand = "Volvo", model = "V60 Polestar Engineered", year = 2024, engine = "2.0L I4 Hybrid", horsepower = 455, transmission = "8-speed Automatic", description = "Performance wagon with plug-in hybrid efficiency.", category = "Hybrid", fuelEfficiency = "74 MPGe", imageUrl = "v60_polestar_engineered"),
                Car(brand = "Lexus", model = "RX 500h", year = 2024, engine = "2.4L I4 Hybrid", horsepower = 366, transmission = "6-speed Automatic", description = "Performance-focused hybrid luxury SUV.", category = "Hybrid", fuelEfficiency = "27 MPG", imageUrl = "rx_500h"),
                Car(brand = "McLaren", model = "P1", year = 2015, engine = "3.8L V8 Hybrid", horsepower = 903, transmission = "7-speed Dual-Clutch", description = "One of the holy trinity, defining hybrid hypercars.", category = "Hybrid", fuelEfficiency = "18 MPGe", imageUrl = "p1"),
                Car(brand = "Porsche", model = "918 Spyder", year = 2015, engine = "4.6L V8 Hybrid", horsepower = 887, transmission = "7-speed PDK", description = "Precision engineering meets hybrid power.", category = "Hybrid", fuelEfficiency = "67 MPGe", imageUrl = "porsche918_spyder"),
                Car(brand = "Ferrari", model = "LaFerrari", year = 2016, engine = "6.3L V12 Hybrid", horsepower = 950, transmission = "7-speed Dual-Clutch", description = "The ultimate Ferrari with race-derived hybrid tech.", category = "Hybrid", fuelEfficiency = "14 MPGe", imageUrl = "laferrari"),
                Car(brand = "Koenigsegg", model = "Regera", year = 2022, engine = "5.0L V8 Hybrid", horsepower = 1500, transmission = "Direct Drive", description = "Luxury hypercar with unique direct drive hybrid tech.", category = "Hybrid", fuelEfficiency = "N/A", imageUrl = "regera"),
                Car(brand = "Mercedes-AMG", model = "One", year = 2023, engine = "1.6L V6 Hybrid", horsepower = 1063, transmission = "8-speed Automated Manual", description = "F1 technology brought to the road.", category = "Hybrid", fuelEfficiency = "N/A", imageUrl = "one"),
                Car(brand = "Toyota", model = "RAV4 Prime", year = 2024, engine = "2.5L I4 Plug-in Hybrid", horsepower = 302, transmission = "eCVT", description = "Practical, efficient, and surprisingly quick crossover.", category = "Hybrid", fuelEfficiency = "94 MPGe", imageUrl = "rav4_prime"),
                Car(brand = "Honda", model = "CR-V Hybrid", year = 2024, engine = "2.0L I4 Hybrid", horsepower = 204, transmission = "eCVT", description = "The versatile SUV that's as efficient as it is comfortable.", category = "Hybrid", fuelEfficiency = "40/34 MPG", imageUrl = "cr_v_hybrid"),
                Car(brand = "Volvo", model = "XC90 Recharge", year = 2024, engine = "2.0L I4 Plug-in Hybrid", horsepower = 455, transmission = "8-speed Automatic", description = "Luxury three-row SUV with powerful plug-in hybrid tech.", category = "Hybrid", fuelEfficiency = "58 MPGe", imageUrl = "xc90_recharge"),
                Car(brand = "Jeep", model = "Grand Cherokee 4xe", year = 2024, engine = "2.0L I4 Plug-in Hybrid", horsepower = 375, transmission = "8-speed Automatic", description = "Legendary 4x4 capability with plug-in hybrid efficiency.", category = "Hybrid", fuelEfficiency = "56 MPGe", imageUrl = "grand_cherokee_4xe"),
                Car(brand = "Chrysler", model = "Pacifica Hybrid", year = 2024, engine = "3.6L V6 Plug-in Hybrid", horsepower = 260, transmission = "eCVT", description = "The only plug-in hybrid minivan on the market.", category = "Hybrid", fuelEfficiency = "82 MPGe", imageUrl = "pacifica_hybrid"),
                Car(brand = "Mitsubishi", model = "Outlander PHEV", year = 2024, engine = "2.4L I4 Plug-in Hybrid", horsepower = 248, transmission = "Single-speed", description = "A unique plug-in hybrid SUV with standard three-row seating.", category = "Hybrid", fuelEfficiency = "64 MPGe", imageUrl = "outlander_phev"),
                Car(brand = "Hyundai", model = "Tucson Hybrid", year = 2024, engine = "1.6L I4 Hybrid", horsepower = 226, transmission = "6-speed Automatic", description = "A stylish and tech-forward compact SUV with hybrid power.", category = "Hybrid", fuelEfficiency = "37/36 MPG", imageUrl = "tucson_hybrid"),
                Car(brand = "Kia", model = "Sorento Hybrid", year = 2024, engine = "1.6L I4 Hybrid", horsepower = 227, transmission = "6-speed Automatic", description = "Efficient and versatile three-row crossover.", category = "Hybrid", fuelEfficiency = "39/35 MPG", imageUrl = "sorento_hybrid"),
                Car(brand = "Ford", model = "Maverick Hybrid", year = 2024, engine = "2.5L I4 Hybrid", horsepower = 191, transmission = "eCVT", description = "The compact truck that redefined efficiency.", category = "Hybrid", fuelEfficiency = "42/33 MPG", imageUrl = "maverick_hybrid"),
                Car(brand = "Lexus", model = "NX 450h+", year = 2024, engine = "2.5L I4 Plug-in Hybrid", horsepower = 304, transmission = "eCVT", description = "A refined luxury compact SUV with plug-in efficiency.", category = "Hybrid", fuelEfficiency = "84 MPGe", imageUrl = "nx_450h"),
                Car(brand = "BMW", model = "i8", year = 2020, engine = "1.5L I3 Hybrid", horsepower = 369, transmission = "6-speed Automatic", description = "A futuristic sports car that proved hybrid performance.", category = "Hybrid", fuelEfficiency = "69 MPGe", imageUrl = "i8"),
                Car(brand = "Lexus", model = "LS 500h", year = 2024, engine = "3.5L V6 Hybrid", horsepower = 354, transmission = "Multi-stage Hybrid", description = "The flagship luxury sedan with a smooth hybrid powertrain.", category = "Hybrid", fuelEfficiency = "22/29 MPG", imageUrl = "ls_500h"),
                Car(brand = "Lamborghini", model = "Countach LPI 800-4", year = 2022, engine = "6.5L V12 Hybrid", horsepower = 802, transmission = "7-speed ISR", description = "A modern hybrid tribute to the legendary Countach.", category = "Hybrid", fuelEfficiency = "11 MPG", imageUrl = "countach_lpi_800_4"),
                Car(brand = "Ferrari", model = "SF90 Stradale", year = 2024, engine = "4.0L V8 Plug-in Hybrid", horsepower = 986, transmission = "8-speed Dual-Clutch", description = "Ferrari's most powerful road car with triple electric motors.", category = "Hybrid", fuelEfficiency = "51 MPGe", imageUrl = "sf90_stradale"),
                Car(brand = "Ferrari", model = "FXX-K Evo", year = 2020, engine = "6.3L V12 Hybrid", horsepower = 1036, transmission = "7-speed Dual-Clutch", description = "An experimental track-only hybrid masterpiece.", category = "Hybrid", fuelEfficiency = "N/A", imageUrl = "fxx_k_evo"),
                Car(brand = "McLaren", model = "Speedtail", year = 2022, engine = "4.0L V8 Hybrid", horsepower = 1035, transmission = "7-speed Dual-Clutch", description = "A three-seat hyper-GT designed for ultimate speed.", category = "Hybrid", fuelEfficiency = "N/A", imageUrl = "speedtail"),
                Car(brand = "Koenigsegg", model = "Gemera", year = 2024, engine = "2.0L I3 Hybrid", horsepower = 1700, transmission = "Single-speed", description = "A four-seat hypercar with insane hybrid power.", category = "Hybrid", fuelEfficiency = "N/A", imageUrl = "gemera"),
                Car(brand = "Aston Martin", model = "Valhalla", year = 2024, engine = "4.0L V8 Hybrid", horsepower = 937, transmission = "8-speed Dual-Clutch", description = "A mid-engine hybrid supercar with F1-inspired tech.", category = "Hybrid", fuelEfficiency = "N/A", imageUrl = "valhalla"),
                Car(brand = "Karma", model = "Revero", year = 2024, engine = "1.5L I3 Range Extender", horsepower = 536, transmission = "Single-speed", description = "Luxury electric vehicle with a range-extending gas engine.", category = "Hybrid", fuelEfficiency = "N/A", imageUrl = "revero"),
                Car(brand = "Polestar", model = "1", year = 2022, engine = "2.0L I4 Hybrid", horsepower = 609, transmission = "8-speed Automatic", description = "A high-performance hybrid GT with a focus on design.", category = "Hybrid", fuelEfficiency = "52 MPGe", imageUrl = "polestar1"),

                // Electric Cars (40)
                Car(brand = "Tesla", model = "Model S Plaid", year = 2024, engine = "Tri-Motor Electric", horsepower = 1020, transmission = "Single-speed", description = "Blistering acceleration and cutting-edge tech.", category = "Electric", fuelEfficiency = "102 MPGe", imageUrl = "modelsplaid"),
                Car(brand = "Porsche", model = "Taycan Turbo S", year = 2024, engine = "Dual Electric Motors", horsepower = 750, transmission = "2-speed Automatic", description = "The electric sports car that sets new standards.", category = "Electric", fuelEfficiency = "70 MPGe", imageUrl = "tycanturbos"),
                Car(brand = "Hyundai", model = "IONIQ 6", year = 2024, engine = "Electric Motor", horsepower = 320, transmission = "Single-speed", description = "Ultra-streamlined design with exceptional range.", category = "Electric", fuelEfficiency = "140 MPGe", imageUrl = "ioniq6"),
                Car(brand = "Rivian", model = "R1T", year = 2024, engine = "Quad-Motor Electric", horsepower = 835, transmission = "Single-speed", description = "The electric truck ready for any adventure.", category = "Electric", fuelEfficiency = "70 MPGe", imageUrl = "rivianr1t"),
                Car(brand = "Audi", model = "e-tron GT", year = 2024, engine = "Dual Electric Motors", horsepower = 637, transmission = "2-speed Automatic", description = "Electric performance meets Audi luxury.", category = "Electric", fuelEfficiency = "85 MPGe", imageUrl = "etrongt"),
                Car(brand = "Lucid", model = "Air Sapphire", year = 2024, engine = "Tri-Motor Electric", horsepower = 1234, transmission = "Single-speed", description = "The pinnacle of electric luxury and performance.", category = "Electric", fuelEfficiency = "105 MPGe", imageUrl = "airsapphire"),
                Car(brand = "Rimac", model = "Nevera", year = 2024, engine = "Quad Electric Motors", horsepower = 1914, transmission = "Single-speed", description = "The world's fastest accelerating production car.", category = "Electric", fuelEfficiency = "53 MPGe", imageUrl = "nevera"),
                Car(brand = "Ford", model = "F-150 Lightning", year = 2024, engine = "Dual Electric Motors", horsepower = 580, transmission = "Single-speed", description = "America's favorite truck, now fully electric.", category = "Electric", fuelEfficiency = "68 MPGe", imageUrl = "f150"),
                Car(brand = "Lotus", model = "Evija", year = 2024, engine = "Quad Electric Motors", horsepower = 1972, transmission = "Single-speed", description = "The first British all-electric hypercar.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "evija"),
                Car(brand = "Pininfarina", model = "Battista", year = 2024, engine = "Quad Electric Motors", horsepower = 1900, transmission = "Single-speed", description = "Pure electric luxury hyper GT from Italy.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "battista"),
                Car(brand = "Lucid", model = "Air Grand Touring", year = 2024, engine = "Dual Electric Motors", horsepower = 819, transmission = "Single-speed", description = "Unmatched range and luxury in an electric sedan.", category = "Electric", fuelEfficiency = "131 MPGe", imageUrl = "air_grand_touring"),
                Car(brand = "Mercedes-Benz", model = "EQS 580", year = 2024, engine = "Dual Electric Motors", horsepower = 516, transmission = "Single-speed", description = "The flagship electric sedan from Mercedes-Benz.", category = "Electric", fuelEfficiency = "92 MPGe", imageUrl = "eqs_580"),
                Car(brand = "Kia", model = "EV6 GT", year = 2024, engine = "Dual Electric Motors", horsepower = 576, transmission = "Single-speed", description = "High-performance electric crossover with stunning speed.", category = "Electric", fuelEfficiency = "79 MPGe", imageUrl = "ev6_gt"),
                Car(brand = "Polestar", model = "2 BST Edition 230", year = 2023, engine = "Dual Electric Motors", horsepower = 476, transmission = "Single-speed", description = "Limited edition performance-tuned electric sedan.", category = "Electric", fuelEfficiency = "100 MPGe", imageUrl = "polestar_2_bst_edition_230"),
                Car(brand = "Tesla", model = "Model 3 Performance", year = 2024, engine = "Dual Electric Motors", horsepower = 510, transmission = "Single-speed", description = "The benchmark for high-performance compact electric sedans.", category = "Electric", fuelEfficiency = "113 MPGe", imageUrl = "model_3_performance"),
                Car(brand = "GMC", model = "Hummer EV", year = 2024, engine = "Tri-Motor Electric", horsepower = 1000, transmission = "Single-speed", description = "Extreme electric off-road capability in a massive package.", category = "Electric", fuelEfficiency = "53 MPGe", imageUrl = "hummer_ev"),
                Car(brand = "BMW", model = "i7 M70", year = 2024, engine = "Dual Electric Motors", horsepower = 650, transmission = "Single-speed", description = "Ultimate electric luxury with M performance.", category = "Electric", fuelEfficiency = "81 MPGe", imageUrl = "i7_m70"),
                Car(brand = "Tesla", model = "Cybertruck Cyberbeast", year = 2024, engine = "Tri-Motor Electric", horsepower = 845, transmission = "Single-speed", description = "Unconventional design with brute electric power.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "cybertruck_cyberbeast"),
                Car(brand = "Polestar", model = "3", year = 2024, engine = "Dual Electric Motors", horsepower = 517, transmission = "Single-speed", description = "Performance SUV for the electric age.", category = "Electric", fuelEfficiency = "80 MPGe", imageUrl = "polestar_3"),
                Car(brand = "Mercedes-Benz", model = "EQS SUV 580", year = 2024, engine = "Dual Electric Motors", horsepower = 536, transmission = "Single-speed", description = "Luxury and space redefined in an all-electric SUV.", category = "Electric", fuelEfficiency = "79 MPGe", imageUrl = "eqs_suv_580"),
                Car(brand = "Chevrolet", model = "Blazer EV SS", year = 2024, engine = "Dual Electric Motors", horsepower = 557, transmission = "Single-speed", description = "All-electric performance in a bold SUV package.", category = "Electric", fuelEfficiency = "90 MPGe", imageUrl = "blazer_ev_ss"),
                Car(brand = "Cadillac", model = "LYRIQ", year = 2024, engine = "Dual Electric Motors", horsepower = 500, transmission = "Single-speed", description = "Redefining Cadillac luxury for the electric era.", category = "Electric", fuelEfficiency = "89 MPGe", imageUrl = "lyriq"),
                Car(brand = "GMC", model = "Sierra EV Denali", year = 2024, engine = "Dual Electric Motors", horsepower = 754, transmission = "Single-speed", description = "Uncompromising capability and luxury in an electric truck.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "sierra_ev_denali"),
                Car(brand = "Volkswagen", model = "ID.4", year = 2024, engine = "Electric Motor", horsepower = 201, transmission = "Single-speed", description = "The electric SUV for the people.", category = "Electric", fuelEfficiency = "107 MPGe", imageUrl = "id_4"),
                Car(brand = "Nissan", model = "Ariya", year = 2024, engine = "Electric Motor", horsepower = 238, transmission = "Single-speed", description = "A refined and futuristic electric crossover.", category = "Electric", fuelEfficiency = "101 MPGe", imageUrl = "ariya"),
                Car(brand = "Volvo", model = "EX90", year = 2024, engine = "Dual Electric Motors", horsepower = 402, transmission = "Single-speed", description = "A new era of safety and luxury in a seven-seat electric SUV.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "ex90"),
                Car(brand = "Polestar", model = "4", year = 2024, engine = "Dual Electric Motors", horsepower = 544, transmission = "Single-speed", description = "A performance SUV coupe with a unique rear-view tech.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "polestar_4"),
                Car(brand = "Fisker", model = "Ocean", year = 2024, engine = "Dual Electric Motors", horsepower = 564, transmission = "Single-speed", description = "Sustainable luxury with innovative solar roof technology.", category = "Electric", fuelEfficiency = "92 MPGe", imageUrl = "ocean"),
                Car(brand = "Lucid", model = "Gravity", year = 2025, engine = "Dual Electric Motors", horsepower = 800, transmission = "Single-speed", description = "The luxury SUV that defies expectations with incredible range.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "gravity"),
                Car(brand = "Tesla", model = "Roadster", year = 2025, engine = "Tri-Motor Electric", horsepower = 1000, transmission = "Single-speed", description = "The quickest car in the world, with record-setting acceleration.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "roadster"),
                Car(brand = "Nio", model = "EP9", year = 2021, engine = "Quad Electric Motors", horsepower = 1341, transmission = "Single-speed", description = "One of the fastest electric cars to ever lap the Nurburgring.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "ep9"),
                Car(brand = "Lotus", model = "Eletre R", year = 2024, engine = "Dual Electric Motors", horsepower = 905, transmission = "2-speed Automatic", description = "The world's first electric hyper-SUV.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "eletre_r"),
                Car(brand = "Rolls-Royce", model = "Spectre", year = 2024, engine = "Dual Electric Motors", horsepower = 577, transmission = "Single-speed", description = "The first ultra-luxury electric super coupe.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "spectre"),
                Car(brand = "BMW", model = "iX M60", year = 2024, engine = "Dual Electric Motors", horsepower = 610, transmission = "Single-speed", description = "A high-performance luxury electric SUV with M power.", category = "Electric", fuelEfficiency = "77 MPGe", imageUrl = "ix_m60"),
                Car(brand = "Audi", model = "Q8 e-tron", year = 2024, engine = "Dual Electric Motors", horsepower = 402, transmission = "Single-speed", description = "A sophisticated and capable electric luxury SUV.", category = "Electric", fuelEfficiency = "80 MPGe", imageUrl = "q8_e_tron"),
                Car(brand = "Mercedes-AMG", model = "EQE 53", year = 2024, engine = "Dual Electric Motors", horsepower = 617, transmission = "Single-speed", description = "Executive luxury with AMG electric performance.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "eqe_53"),
                Car(brand = "Genesis", model = "GV60 Performance", year = 2024, engine = "Dual Electric Motors", horsepower = 483, transmission = "Single-speed", description = "A bold and high-tech electric luxury crossover.", category = "Electric", fuelEfficiency = "90 MPGe", imageUrl = "gv60_performance"),
                Car(brand = "Polestar", model = "5", year = 2025, engine = "Dual Electric Motors", horsepower = 884, transmission = "Single-speed", description = "The high-performance electric 4-door GT.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "polestar_5"),
                Car(brand = "Faraday Future", model = "FF 91", year = 2024, engine = "Tri-Motor Electric", horsepower = 1050, transmission = "Single-speed", description = "A high-tech electric luxury vehicle with extreme performance.", category = "Electric", fuelEfficiency = "N/A", imageUrl = "ff_91"),
                Car(brand = "Rivian", model = "R1S", year = 2024, engine = "Quad-Motor Electric", horsepower = 835, transmission = "Single-speed", description = "The seven-seat electric SUV that can go anywhere.", category = "Electric", fuelEfficiency = "69 MPGe", imageUrl = "r1s")
            )
            repository.deleteAll()
            repository.insertAll(sampleCars)
        }
    }
}

class CarViewModelFactory(private val repository: CarRepository) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(CarViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return CarViewModel(repository) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}
